// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using NBA.EFCore.OfficialProvider;
using System;

namespace NBA.EFCore.OfficialProvider.Migrations
{
    [DbContext(typeof(TestContext))]
    partial class TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("NBA.EFCore.OfficialProvider.PlayerModel", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Addition");

                    b.Property<string>("assists_per_game");

                    b.Property<string>("blocks_per_game");

                    b.Property<string>("defensive_rebounds_per_game");

                    b.Property<string>("field_goal_percentage");

                    b.Property<string>("field_goals_attempted_per_game");

                    b.Property<string>("field_goals_made_per_game");

                    b.Property<string>("free_throw_percentage");

                    b.Property<string>("games_played");

                    b.Property<string>("minutes_per_game");

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<string>("offensive_rebounds_per_game");

                    b.Property<string>("player_efficiency_rating");

                    b.Property<string>("points_per_game");

                    b.Property<string>("rebounds_per_game");

                    b.Property<string>("steals_per_game");

                    b.Property<string>("team_acronym");

                    b.Property<string>("team_name");

                    b.Property<string>("three_point_attempted_per_game");

                    b.Property<string>("three_point_made_per_game");

                    b.Property<string>("three_point_percentage");

                    b.Property<string>("turnovers_per_game");

                    b.HasKey("id");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
